apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci-app
  template:
    metadata:
      labels:
        app: fibonacci-app
    spec:
      containers:
        - name: fibonacci-app
          image: fibonacciapp:1.0
          imagePullPolicy: Never